//! The Rust emitter.
//!
//! For each function, one generated file containing:
//!
//! * a doc comment with every fact the tooling could recover (address range,
//!   size, frame layout, saved registers, callees, data references, original
//!   source path when `.mdebug` has it, and an explicit "what makes this hard"
//!   line),
//! * the raw disassembly, which is the ground truth for a behavioural rewrite,
//! * a compilable stub with an inferred signature and `todo!()`.
//!
//! plus a sibling `.sketch.rs.txt` with a per-instruction Rust transliteration
//! (see [`crate::translit`]) that is *not* meant to compile — it is the starting
//! point a human edits into idiomatic Rust.
//!
//! Re-running the generator never overwrites a curated file: files whose stub
//! marker is gone (a human edited them) are skipped unless `--force`, and
//! functions recorded as `done` in the status file are skipped entirely. That
//! makes `gowd gen` safe inside an edit/compile loop.

use std::fmt::Write as _;
use std::path::Path;

use ps2_elf::sanitize_ident;

use crate::analyze::{Confidence, FunctionAnalysis};
use crate::status;

/// Marker line that identifies a file as still machine-owned.
pub const STUB_MARKER: &str = "@gowd-stub";

pub struct EmitOptions {
    /// Emit `todo!()` bodies even for functions already marked done.
    pub force: bool,
    /// Include the full disassembly listing in each file.
    pub listing: bool,
    /// Max instructions to print in the listing before eliding.
    pub listing_limit: usize,
}

impl Default for EmitOptions {
    fn default() -> Self {
        Self {
            force: false,
            listing: true,
            listing_limit: 400,
        }
    }
}

pub struct Emitted {
    pub name: String,
    pub path: std::path::PathBuf,
    pub action: Action,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Action {
    Created,
    Refreshed,
    /// Left alone because a human owns the file now.
    SkippedEdited,
    /// Left alone because the status file says it is done.
    SkippedDone,
    /// Not emitted (no bytes, filtered out).
    Skipped,
}

/// Header written at the top of every generated module file, so a reader can
/// tell provenance instantly and `cargo build` stays warning-free.
fn prelude() -> String {
    let mut s = String::new();
    s.push_str("//! Generated by `gowd gen` — do not hand-edit this file.\n");
    s.push_str("//!\n");
    s.push_str("//! It contains one decompilation unit: a documented stub whose body\n");
    s.push_str("//! you replace with idiomatic Rust. Delete the `@gowd-stub` line below\n");
    s.push_str("//! once you start editing, and `gowd gen` will leave the file alone.\n");
    s.push_str("//!\n");
    s.push_str("//! The `.sketch.rs.txt` sibling is a mechanical transliteration of the\n");
    s.push_str("//! machine code (with MIPS delay slots folded in); it does not compile\n");
    s.push_str("//! and is reference material only.\n");
    s
}

/// The Rust source for one function.
pub fn function_source(a: &FunctionAnalysis, opts: &EmitOptions) -> String {
    let ident = sanitize_ident(&a.name);
    let mut s = String::new();
    s.push_str(&prelude());
    s.push_str(&format!("// {STUB_MARKER} {}\n\n", a.address));

    // ---- doc comment: everything we know ----
    let mut doc = String::new();
    let _ = writeln!(
        doc,
        "/// Recovered from `{:#010x}` ({:#x} bytes, {} instructions).",
        a.address,
        a.byte_len(),
        a.instruction_count()
    );
    if let Some(f) = &a.source_file {
        let _ = writeln!(doc, "/// Original source: `{f}`");
    }
    let _ = writeln!(
        doc,
        "/// Frame: {:#x} bytes ({}), saves: {}",
        a.frame_size,
        if a.frame_from_symbol {
            "from symbol table"
        } else {
            "inferred from prologue"
        },
        if a.saved_regs.is_empty() {
            "none".to_string()
        } else {
            a.saved_regs
                .iter()
                .map(|r| format!("`${}`", ee_isa::GPR_ABI[*r as usize]))
                .collect::<Vec<_>>()
                .join(" ")
        }
    );
    if !a.calls.is_empty() {
        let _ = writeln!(
            doc,
            "/// Calls: {}",
            a.calls
                .iter()
                .take(12)
                .map(|c| match &c.name {
                    Some(n) => format!("`{n}`"),
                    None => format!("`f_{:08x}`", c.addr),
                })
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    if !a.data_refs.is_empty() {
        let _ = writeln!(
            doc,
            "/// Data references ($gp-relative): {}",
            a.data_refs
                .iter()
                .take(12)
                .map(|d| match &d.name {
                    Some(n) => format!("`{n}`"),
                    None => format!("`{:#010x}`", d.addr),
                })
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    let _ = writeln!(
        doc,
        "///\n/// Difficulty: {}. Undecoded words: {}. Confidence: {:?}.",
        a.difficulty(),
        a.unknown_count,
        a.confidence
    );
    s.push_str(&doc);
    s.push_str("#![allow(dead_code, non_snake_case, unused_variables, unused_unsafe)]\n\n");

    // ---- signature ----
    let params = signature_params(a);
    s.push_str(&format!("pub unsafe fn {ident}({params}) -> u32 {{\n"));

    // ---- disassembly ----
    if opts.listing {
        s.push_str("    // ---- original R5900 instructions (behaviour reference) ----\n");
        for (printed, ins) in a.insns.iter().enumerate() {
            if printed == opts.listing_limit {
                s.push_str(&format!(
                    "    // ... {} more instructions (use `gowd disasm --name {}`)\n",
                    a.insns.len() - printed,
                    a.name
                ));
            }
            let note = if ins.is_unknown() {
                "  // ??? not decoded"
            } else {
                ""
            };
            s.push_str(&format!(
                "    // {:08x}: {:08x}  {:<34}{note}\n",
                ins.addr,
                ins.raw,
                ins.text(&ee_isa::DecodeOptions::listing()),
            ));
        }
    }

    // ---- body ----
    if a.unknown_count > 0 {
        s.push_str(&format!(
            "    // NOTE: {} instruction(s) here are not recognised by `ee-isa`.\n\
             //       Add them to crates/ee-isa (with a binutils-verified encoding)\n\
             //       before rewriting this function, or they will be lost.\n",
            a.unknown_count
        ));
    }
    s.push_str("    // TODO: reimplement the behaviour above in idiomatic Rust, then\n");
    s.push_str("    // mark this function `done` in the status file and delete the\n");
    s.push_str("    // `@gowd-stub` line so `gowd gen` stops touching this file.\n");
    s.push_str(&format!(
        "    todo!(\"{ident}: {:#010x}\")\n}}\n",
        a.address
    ));
    s
}

/// O32: `$a0..$a3` then the stack. With STABS parameter names we use them and
/// give everything the `u32`-sized "opaque word" type, since ECOFF type-graph
/// resolution is a later milestone — a deliberate choice over inventing types.
fn signature_params(a: &FunctionAnalysis) -> String {
    let mut parts: Vec<String> = Vec::new();
    if !a.params.is_empty() {
        for (name, raw) in a.params.iter().take(4) {
            let ident = sanitize_ident(name);
            parts.push(format!("{ident}: u32 /* {raw} */"));
        }
    } else {
        // Register-only arguments; the caller may pass more via the stack, which
        // the emitter cannot know without a prototype.
        let used = used_arg_regs(a);
        for r in 4..4 + used {
            parts.push(format!("{}: u32", ee_isa::GPR_ABI[r]));
        }
    }
    if parts.is_empty() {
        return String::new();
    }
    parts.join(", ")
}

/// How many of `$a0..$a3` are read without first being overwritten: the prefix
/// of argument registers the body actually consumes. This is evidence, not
/// proof — a `va_arg` callee or a struct returned in registers can use fewer —
/// so the emitter documents the guess in the generated file.
fn used_arg_regs(a: &FunctionAnalysis) -> usize {
    let mut read = [false; 4];
    let mut written = [false; 4];
    for ins in &a.insns {
        for r in ins.reads_gprs() {
            if (4..8).contains(&r) {
                read[(r - 4) as usize] = true;
            }
        }
        if let Some(r) = ins.writes_gpr() {
            if (4..8).contains(&r) {
                written[(r - 4) as usize] = true;
            }
        }
    }
    let mut n = 0;
    for i in 0..4 {
        if read[i] && !written[i] {
            n = i + 1;
        } else {
            break;
        }
    }
    n
}

/// The non-compiling per-instruction transliteration.
pub fn sketch_source(a: &FunctionAnalysis) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "// Transliteration sketch for `{}` @ {:#010x} — reference material, NOT Rust.\n\
         // Generated by `gowd gen`; regenerate instead of editing.\n\
         // Uses `goto L_<addr>` because the original code has MIPS delay slots and\n\
         // unstructured branches; restructuring is the human's job.\n\n",
        a.name, a.address
    ));
    s.push_str(&format!("unsafe fn {}() {{\n", sanitize_ident(&a.name)));
    s.push_str(&crate::translit::decls(crate::translit::Style::Abi));
    for (addr, lines) in crate::translit::sketch(&a.insns, crate::translit::Style::Abi) {
        s.push_str(&format!("    // {addr:08x}\n"));
        for l in lines {
            s.push_str(&format!("    {l}\n"));
        }
    }
    s.push_str("}\n");
    s
}

/// Write every function file for a project, honouring the ownership rules.
pub fn generate(
    out_dir: &Path,
    funcs: &[FunctionAnalysis],
    st: &status::StatusFile,
    opts: &EmitOptions,
) -> Result<Vec<Emitted>, String> {
    let gen = out_dir.join("gen");
    std::fs::create_dir_all(&gen).map_err(|e| format!("{}: {e}", gen.display()))?;
    let sketch_dir = out_dir.join("sketches");
    std::fs::create_dir_all(&sketch_dir).map_err(|e| format!("{}: {e}", sketch_dir.display()))?;

    let mut emitted = Vec::new();
    let mut mod_names: Vec<(String, String)> = Vec::new();

    for a in funcs {
        let ident = sanitize_ident(&a.name);
        if ident.is_empty() {
            emitted.push(Emitted {
                name: a.name.clone(),
                path: gen.clone(),
                action: Action::Skipped,
            });
            continue;
        }
        let path = gen.join(format!("{ident}.rs"));
        let done = st.is_done(a.address);
        if done && !opts.force {
            emitted.push(Emitted {
                name: a.name.clone(),
                path: path.clone(),
                action: Action::SkippedDone,
            });
            mod_names.push((ident.clone(), a.name.clone()));
            continue;
        }
        let src = function_source(a, opts);
        let action = match std::fs::read_to_string(&path) {
            Ok(existing) if existing.contains(STUB_MARKER) || opts.force => {
                std::fs::write(&path, &src).map_err(|e| format!("{}: {e}", path.display()))?;
                Action::Refreshed
            }
            Ok(_) => Action::SkippedEdited,
            Err(_) => {
                std::fs::write(&path, &src).map_err(|e| format!("{}: {e}", path.display()))?;
                Action::Created
            }
        };
        // The sketch always regenerates: it is derived, disposable, and cheap.
        let spath = sketch_dir.join(format!("{ident}.rs.txt"));
        let _ = std::fs::write(&spath, sketch_source(a));
        emitted.push(Emitted {
            name: a.name.clone(),
            path,
            action,
        });
        mod_names.push((ident, a.name.clone()));
    }

    // mod.rs — declares every generated module so `cargo build` type-checks
    // the whole recovered tree at once.
    let mut m = String::new();
    m.push_str("//! Generated by `gowd gen` — the recovered-code module tree.\n\n");
    for (ident, name) in &mod_names {
        m.push_str(&format!("/// `{name}`\npub mod {ident};\n"));
    }
    std::fs::write(gen.join("mod.rs"), m).map_err(|e| format!("mod.rs: {e}"))?;
    Ok(emitted)
}

/// A one-line human-readable summary, used by `gowd gen`'s progress output.
#[must_use]
pub fn summary(a: &FunctionAnalysis) -> String {
    let conf = match a.confidence {
        Confidence::Symbolised => "sym",
        Confidence::Inferred => "inf",
        Confidence::Anonymous => "anon",
    };
    format!(
        "{:#010x} {:>6} {:>4} {:<8} {:>3}u {:>3}c {}",
        a.address,
        format!("{:#x}", a.byte_len()),
        a.instruction_count(),
        conf,
        a.unknown_count,
        a.calls.len(),
        a.name
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fake() -> FunctionAnalysis {
        use ee_isa::{decode_all, DecodeOptions};
        let code: Vec<u8> = [
            0x27bd_ffe0u32, // addiu $sp,$sp,-32
            0xafbf001c,     // sw $ra,28($sp)
            0x0080_4825,    // or $t1,$a1,$zero  (move)
            0x03e0_0008,    // jr $ra
            0x0000_0000,    // nop in the delay slot
        ]
        .iter()
        .flat_map(|w| w.to_le_bytes())
        .collect();
        let insns = decode_all(0x1000, &code, &DecodeOptions::raw());
        FunctionAnalysis {
            name: "test_fn".into(),
            address: 0x1000,
            end: 0x1000 + code.len() as u32,
            insns,
            frame_size: 32,
            frame_from_symbol: false,
            saved_regs: vec![31],
            slots: vec![],
            calls: vec![],
            indirect_jumps: vec![],
            labels: vec![0x1004],
            data_refs: vec![],
            uses_fpu: false,
            uses_mmi: false,
            uses_stack: true,
            unknown_count: 0,
            confidence: Confidence::Inferred,
            params: vec![],
            stabs_locals: None,
            return_type: None,
            source_file: Some("test.c".into()),
            decode_note: None,
        }
    }

    fn _unused(_: &FunctionAnalysis) {}

    #[test]
    fn emits_a_documented_stub() {
        let a = fake();
        let src = function_source(&a, &EmitOptions::default());
        assert!(src.contains("@gowd-stub"));
        assert!(src.contains("pub unsafe fn test_fn("), "{src}");
        assert!(src.contains("todo!"));
        assert!(
            src.contains("00001000: 27bdffe0"),
            "listing missing:\n{src}"
        );
        assert!(src.contains("test.c"));
        // Must be pasteable Rust: balanced braces.
        assert_eq!(src.matches('{').count(), src.matches('}').count(), "{src}");
    }

    #[test]
    fn signature_uses_arg_registers_when_no_stabs() {
        let a = fake();
        let src = function_source(&a, &EmitOptions::default());
        assert!(src.contains("a0: u32"), "expected $a0 in signature:\n{src}");
        assert!(!src.contains("a1: u32"), "$a1 is never read:\n{src}");
    }

    #[test]
    fn sketch_marks_delay_slots_and_returns() {
        let a = fake();
        let sk = sketch_source(&a);
        assert!(sk.contains("delay slot"), "{sk}");
        assert!(sk.contains("return v0;"), "{sk}");
        assert!(sk.contains("let mut sp : u32 = 0;"));
    }
}
